# broadcast control system
version: '3.4'

services:
  icecast:
    image: api.wjrh.org:5000/icecast
    ports: ["8000:8000"]
    deploy:
      placement:
        constraints:
          - "node.labels.name==api"

  broadcast-control:
    image: api.wjrh.org:5000/broadcast-control
    deploy:
      placement:
        constraints:
          - "node.labels.name==desktop"

  robodj:
    image: api.wjrh.org:5000/robodj
    volumes:
      - /home/connor/Music/Non-Album:/media/songs
    deploy:
      placement:
        constraints:
          - "node.labels.name==desktop"
