from alpine:latest as repository
run apk add --no-cache git
add "https://api.github.com/repos/WJRH-Engineering/robo-dj/commits?per_page=1" latest_commit
run git clone --recurse-submodules https://github.com/WJRH-Engineering/robo-dj.git src
workdir src

from docker.io/savonet/liquidsoap:v2.0.3 as main

# copy source files
copy --from=repository src/main.liq main.liq
copy --from=repository src/lib lib
copy secrets/passwords.liq secrets/passwords.liq

cmd ["main.liq"]
