# toml file for general configuration of the streaming server

[schedule]
year = 2021
season = "SPRING"

[database]
hostname = "api.wjrh.org"
port = 5432
database = "production"
user = "wjrh"
schedule_table = "schedule"
auth_table = "mountpoints"

# Extra Timeslots

[[timeslot]]
shortname = "sports-broadcasting"
time_range = "0w0h-8w0h"

[scheduler]
"input.server" = "icecast"
"input.port" = 8000
"output.server" = "api.wjrh.org"
"output.port" = 8000
